package ooxml

// Open XML namespaces.
const (
	NSContentTypes         = "http://schemas.openxmlformats.org/package/2006/content-types"
	NSRelationships        = "http://schemas.openxmlformats.org/package/2006/relationships"
	NSOfficeRel            = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
	NSOfficeRelImage       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/image"
	NSOfficeRelHyperlink   = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink"
	NSOfficeRelHeader      = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/header"
	NSOfficeRelFooter      = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer"
	NSOfficeRelNumbering   = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering"
	NSOfficeRelStyles      = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
	NSOfficeRelSettings    = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings"
	NSOfficeRelWebSettings = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings"
	NSOfficeRelFontTable   = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable"
	NSOfficeRelTheme       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme"
	NSOfficeRelOfficeDoc   = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
	NSOfficeRelFootnotes   = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/footnotes"
	NSOfficeRelEndnotes    = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/endnotes"
	NSOfficeRelComments    = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments"
	NSOfficeRelChart       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart"
	NSOfficeRelOleObject   = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/oleObject"
	NSCorePropsRel         = "http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties"
	NSExtPropsRel          = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties"
	NSCustomPropsRel       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties"

	NSW       = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
	NSR       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
	NSWP      = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
	NSA       = "http://schemas.openxmlformats.org/drawingml/2006/main"
	NSC       = "http://schemas.openxmlformats.org/drawingml/2006/chart"
	NSPic     = "http://schemas.openxmlformats.org/drawingml/2006/picture"
	NSM       = "http://schemas.openxmlformats.org/officeDocument/2006/math"
	NSV       = "urn:schemas-microsoft-com:vml"
	NSO       = "urn:schemas-microsoft-com:office:office"
	NSW10     = "urn:schemas-microsoft-com:office:word"
	NSVE      = "http://schemas.openxmlformats.org/markup-compatibility/2006"
	NSWNE     = "http://schemas.microsoft.com/office/word/2006/wordml"
	NSCP      = "http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
	NSDC      = "http://purl.org/dc/elements/1.1/"
	NSDCTERMS = "http://purl.org/dc/terms/"
	NSDCMI    = "http://purl.org/dc/dcmitype/"
	NSXSI     = "http://www.w3.org/2001/XMLSchema-instance"
	NSEPov    = "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"
	NSVT      = "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"
	NSCust    = "http://schemas.openxmlformats.org/officeDocument/2006/custom-properties"

	CTDocument    = "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"
	CTStyles      = "application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"
	CTSettings    = "application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"
	CTWebSettings = "application/vnd.openxmlformats-officedocument.wordprocessingml.webSettings+xml"
	CTFontTable   = "application/vnd.openxmlformats-officedocument.wordprocessingml.fontTable+xml"
	CTNumbering   = "application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"
	CTHeader      = "application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"
	CTFooter      = "application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"
	CTFootnotes   = "application/vnd.openxmlformats-officedocument.wordprocessingml.footnotes+xml"
	CTEndnotes    = "application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml"
	CTComments    = "application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml"
	CTChart       = "application/vnd.openxmlformats-officedocument.drawingml.chart+xml"
	CTTheme       = "application/vnd.openxmlformats-officedocument.theme+xml"
	CTCore        = "application/vnd.openxmlformats-package.core-properties+xml"
	CTApp         = "application/vnd.openxmlformats-officedocument.extended-properties+xml"
	CTCustom      = "application/vnd.openxmlformats-officedocument.custom-properties+xml"
	CTRels        = "application/vnd.openxmlformats-package.relationships+xml"
)
